Code review
FlockOfBirds/dropdown-type-ahead pull request #2
Opened 2018-09-17 11:53 UTC by Stanley-Okwii

2018-09-19 10:36 UTC, McDoyen requested changes
Great work 👍

2018-09-19 10:36 UTC, McDoyen commented on .gitignore
> +.vscode
Should be in global git ignore

2018-09-19 10:36 UTC, McDoyen commented on Gruntfile.js
> +                tasks: [ "webpack:develop", "file_append", "compress:dist", "copy" ],
Remove dist.

2018-09-19 10:36 UTC, McDoyen commented on README.md
> +# Dropdown TypeAhead Reference
If `TypeAhead` is one word, shouldn't it be `Typeahead`??
Where is reference coming from?

2018-09-19 10:36 UTC, McDoyen commented on README.md
> +An input widget that can be used to display and edit associations
An input widget used to display and edit associations

2018-09-19 10:36 UTC, McDoyen commented on development.md
> + Or get the test project from [https://github.com/mendixlabs/dropdown-type-ahead/releases]
Should be /latest

2018-09-19 10:36 UTC, McDoyen commented on development.md
> +  > karma start
This file is incomplete check with other projects

2018-09-19 10:36 UTC, McDoyen commented on package.json
> +    "url": "https://github.com/mendixlabs/dropdown-type-ahead.git"
"url": "https://github.com/mendixlabs/dropdown-type-ahead"

2018-09-19 10:36 UTC, McDoyen commented on package.json
> +    "@types/react-select": "^1.3.0",
install under types

2018-09-19 10:36 UTC, McDoyen commented on src/DropdownTypeahead.webmodeler.ts
> +export class preview extends Component<ContainerProps, {}> {
Empty braces are not necessary

2018-09-19 10:36 UTC, McDoyen commented on src/DropdownTypeahead.webmodeler.ts
> +        return createElement(DropdownTypeahead as any, {
Why use as any? Add all required properties and remove the properties that do not exit on DropdownTypeaheadProps

2018-09-19 10:36 UTC, McDoyen commented on src/DropdownTypeahead.xml
> +    <description></description>
Add description

2018-09-19 10:36 UTC, McDoyen commented on src/DropdownTypeahead.xml
> +        <property key="emptyOptionCaption" type="string" required="false">
make translatableString

2018-09-19 10:36 UTC, McDoyen commented on src/DropdownTypeahead.xml
> +            <caption>Sort options</caption>
Have a uniform naming

2018-09-19 10:36 UTC, McDoyen commented on src/DropdownTypeahead.xml
> +                    <caption>Attribute</caption>
Same here

2018-09-19 10:36 UTC, McDoyen commented on src/DropdownTypeahead.xml
> +            <description>Microflow executed on change selection</description>
Can be rephrased better

2018-09-19 10:36 UTC, McDoyen commented on src/DropdownTypeahead.xml
> +        </property>
Can be rephrased better

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeahead.ts
> +export type MetaData = {
Where is `MetaData` used?
Is this a type or an interface

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeahead.ts
> +export interface AttributeType {
Not used in this file. Best you create is where its used.

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeahead.ts
> +        return this.renderForm();
Why do you create another function to render the form. You could have just returned it?

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeahead.ts
> +                        ...commonProps }) :
Formatting

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeaheadContainer.ts
> +        return createElement(DropdownTypeahead as any, {
Use proper types

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeaheadContainer.ts
> +        if (newProps.mxObject && (newProps.mxObject !== this.props.mxObject)) {
`if (newProps.mxObject !== this.props.mxObject) {`

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeaheadContainer.ts
> +                callback: this.handleSubscriptions,
Arrange then as they r arranged in the api

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeaheadContainer.ts
> +                attr: this.association,
Arrange then as they are arranged in the api

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeaheadContainer.ts
> +                error: error => window.mx.ui.error(`Error while executing microflow ${onChangeMicroflow}: ${error.message}`), // tslint:disable-line max-line-length
Format code and remove that comment

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeaheadContainer.ts
> +                params: {
use `context` instead of params
Arrange same way as the api

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeaheadContainer.ts
> +                origin: mxform
Arrange same way as the api

2018-09-19 10:36 UTC, McDoyen commented on src/components/__tests__/Alert.spec.ts
> +        const alert = renderAlert({ className: "widget-color-picker-alert" }, alertMessage);
dropdown typeahead not color picker

2018-09-19 10:36 UTC, McDoyen commented on src/components/__tests__/Alert.spec.ts
> +        expect(alert).toHaveClass("widget-color-picker-alert");
dropdown typeahead not color picker

2018-09-19 10:36 UTC, McDoyen commented on src/components/__tests__/DropdownTypeahead.spec.ts
> +                    onChange: jasmine.any(Function) as any,
Use as any only when necessary

2018-09-19 10:36 UTC, McDoyen commented on src/components/__tests__/DropdownTypeahead.spec.ts
> +        it("renders with the structure with a no value", () => {
it("renders with the structure with no value", () => {

2018-09-19 10:36 UTC, McDoyen commented on src/components/__tests__/DropdownTypeahead.spec.ts
> +    it("that is still loading renders with the structure", () => {
Put it outside for proper grammar

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeahead.ts
> +                        className: "widget-dropdown-type-ahead-alert"
Shouldn't it be `className: "widget-dropdown-typeahead-alert"` ?
`typeahead` is one word.

2018-09-19 10:36 UTC, McDoyen commented on src/utils/ContainerUtils.ts
> +        window.console.log("Failed to parse style", style, error);
Use `logError`

2018-09-19 10:36 UTC, McDoyen commented on src/utils/Data.ts
> +export interface FetchedData {
Where is this interface used?

2018-09-19 10:36 UTC, McDoyen commented on src/utils/Data.ts
> +            } else if (options.source === "nanoflow" && options.nanoflow && options.mxform) { // nanoflow
Check if the nanoflow itself exists. Nanoflow is an object

2018-09-19 10:36 UTC, McDoyen commented on src/utils/Data.ts
> +            callback: (result) => resolve(result as any),
Order

2018-09-19 10:36 UTC, McDoyen commented on src/utils/Data.ts
> +            callback:  (result) => resolve(result as any),
Order

2018-09-19 10:36 UTC, McDoyen commented on tests/e2e/DropdownTypeahead.spec.ts
> +describe("Dropdown type ahead ", () => {
One word

2018-09-19 10:36 UTC, McDoyen commented on tests/e2e/DropdownTypeahead.spec.ts
> +        homePage.open();
`homePage` is already open

2018-09-19 10:36 UTC, McDoyen commented on tests/e2e/DropdownTypeahead.spec.ts
> +        homePage.dropDownSelector.waitForExist();
It already exists

2018-09-19 10:36 UTC, McDoyen commented on tests/e2e/DropdownTypeahead.spec.ts
> +        homePage.open();
Already open

2018-09-19 10:36 UTC, McDoyen commented on tests/e2e/DropdownTypeahead.spec.ts
> +        homePage.dropDownSelector.waitForExist();
already exists

2018-09-19 10:36 UTC, McDoyen commented on tsconfig.json
> +    "strict": true,
https://www.typescriptlang.org/docs/handbook/compiler-options.html

2018-09-19 10:36 UTC, McDoyen commented on src/components/DropdownTypeahead.ts
> +export type ReferenceOption = {
Is this a type or an interface

2018-09-19 10:36 UTC, McDoyen commented on tslint.json
> +{
Seems to be old. Update from latest code

2018-09-19 10:36 UTC, McDoyen commented on typings/react-fastclick.d.ts
> +declare module "react-fastclick";
https://www.npmjs.com/package/@types/fastclick

2018-09-19 10:36 UTC, McDoyen commented on webpack.config.js
> +module.exports = [ widgetConfig, previewConfig];
space required

2018-09-19 11:18 UTC, McDoyen requested changes

2018-09-19 11:18 UTC, McDoyen commented on webpack.config.js
> +        new CopyWebpackPlugin([ { from: "src/**/*.xml" }], { copyUnmodified: true }),
missing space

2018-09-20 07:54 UTC, Stanley-Okwii commented on Gruntfile.js
> +                tasks: [ "webpack:develop", "file_append", "compress:dist", "copy" ],
Done

2018-09-20 07:55 UTC, Stanley-Okwii commented on README.md
> +# Dropdown TypeAhead Reference
Done

2018-09-20 07:57 UTC, Stanley-Okwii commented on development.md
> + Or get the test project from [https://github.com/mendixlabs/dropdown-type-ahead/releases]
Done

2018-09-20 07:59 UTC, Stanley-Okwii commented on src/components/DropdownTypeahead.ts
> +export type ReferenceOption = {
its a type

2018-09-20 08:20 UTC, Stanley-Okwii commented on webpack.config.js
> +        new CopyWebpackPlugin([ { from: "src/**/*.xml" }], { copyUnmodified: true }),
Fixed

2018-09-20 08:20 UTC, Stanley-Okwii commented on webpack.config.js
> +module.exports = [ widgetConfig, previewConfig];
Fixed

2018-09-20 09:54 UTC, Stanley-Okwii commented on .gitignore
> +.vscode
Done

2018-09-20 10:15 UTC, Stanley-Okwii commented on README.md
> +An input widget that can be used to display and edit associations
Done

2018-11-26 07:09 UTC, Andries-Smit commented
PR not relevant any longer, opened trough new branche, including reference set

2018-11-26 07:09 UTC, closed without merging